// Renders a synthesized Report into HTML (for SES) and plain text (multipart
// fallback + SNS alert bodies).
import type { Issue, Report, Severity } from "./types.js";

const SEVERITY_COLOR: Record<Severity, string> = {
  critical: "#b00020",
  high: "#d93025",
  medium: "#f9a825",
  low: "#1a73e8",
  info: "#5f6368",
};

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function issueHtml(issue: Issue): string {
  const color = SEVERITY_COLOR[issue.severity];
  const evidence = issue.evidence
    .slice(0, 5)
    .map((e) => `<li><code>${esc(e)}</code></li>`)
    .join("");
  const resources = issue.affectedResources.map(esc).join(", ");
  return `
    <tr>
      <td style="padding:12px;border-bottom:1px solid #eee;vertical-align:top">
        <span style="display:inline-block;padding:2px 8px;border-radius:4px;color:#fff;
          background:${color};font-size:12px;text-transform:uppercase">${issue.severity}</span>
        <strong style="margin-left:8px">${esc(issue.title)}</strong>
        <div style="color:#444;margin:6px 0">${esc(issue.description)}</div>
        ${resources ? `<div style="font-size:12px;color:#666">Affected: ${resources}</div>` : ""}
        ${issue.occurrences ? `<div style="font-size:12px;color:#666">Occurrences: ${issue.occurrences}</div>` : ""}
        ${evidence ? `<ul style="margin:6px 0;font-size:12px;color:#333">${evidence}</ul>` : ""}
        <div style="font-size:13px;color:#0b6"><strong>Recommendation:</strong> ${esc(issue.recommendation)}</div>
        <div style="font-size:11px;color:#999;margin-top:4px">source: ${issue.source}</div>
      </td>
    </tr>`;
}

export function renderHtml(report: Report): string {
  const headerColor = SEVERITY_COLOR[report.overallSeverity];
  const statusRows = report.sourceStatus
    .map(
      (s) =>
        `<tr><td style="padding:4px 12px">${esc(s.source)}</td>
         <td style="padding:4px 12px">${s.healthy ? "✅ healthy" : "⚠️ unreachable"}</td>
         <td style="padding:4px 12px">${s.issueCount} issue(s)</td></tr>`,
    )
    .join("");
  const issuesHtml = report.issues.map(issueHtml).join("") ||
    `<tr><td style="padding:12px;color:#0b6">No issues detected in this window. ✅</td></tr>`;

  return `<!DOCTYPE html><html><body style="font-family:Arial,Helvetica,sans-serif;color:#202124;margin:0;padding:0;background:#f5f5f5">
  <div style="max-width:760px;margin:0 auto;background:#fff">
    <div style="background:${headerColor};color:#fff;padding:20px">
      <h1 style="margin:0;font-size:20px">Log Analysis Report — ${report.overallSeverity.toUpperCase()}</h1>
      <div style="opacity:.9;font-size:13px;margin-top:4px">
        ${esc(report.generatedAt)} · last ${report.windowMinutes} min
      </div>
    </div>
    <div style="padding:20px">
      <p style="font-size:15px;line-height:1.5">${esc(report.executiveSummary)}</p>
      <h2 style="font-size:15px;border-bottom:2px solid #eee;padding-bottom:6px">Source status</h2>
      <table style="border-collapse:collapse;font-size:13px;width:100%">${statusRows}</table>
      <h2 style="font-size:15px;border-bottom:2px solid #eee;padding-bottom:6px;margin-top:24px">
        Issues (${report.issues.length})
      </h2>
      <table style="border-collapse:collapse;width:100%">${issuesHtml}</table>
    </div>
    <div style="padding:14px 20px;color:#999;font-size:11px;border-top:1px solid #eee">
      Generated by the Bedrock Agentic Log Analysis system.
    </div>
  </div></body></html>`;
}

export function renderText(report: Report): string {
  const lines: string[] = [
    `LOG ANALYSIS REPORT — ${report.overallSeverity.toUpperCase()}`,
    `${report.generatedAt} · last ${report.windowMinutes} min`,
    "",
    report.executiveSummary,
    "",
    "SOURCE STATUS:",
    ...report.sourceStatus.map(
      (s) => `  - ${s.source}: ${s.healthy ? "healthy" : "UNREACHABLE"} (${s.issueCount} issues)`,
    ),
    "",
    `ISSUES (${report.issues.length}):`,
  ];
  if (report.issues.length === 0) lines.push("  None detected. ✅");
  for (const i of report.issues) {
    lines.push(
      "",
      `  [${i.severity.toUpperCase()}] ${i.title}  (${i.source})`,
      `    ${i.description}`,
      i.affectedResources.length ? `    Affected: ${i.affectedResources.join(", ")}` : "",
      `    Recommendation: ${i.recommendation}`,
    );
  }
  return lines.filter((l) => l !== undefined).join("\n");
}

/** Compact text body for an SNS alert covering only the actionable issues. */
export function renderAlertText(report: Report, issues: Issue[]): string {
  const lines = [
    `🚨 ${issues.length} alert-worthy issue(s) — overall ${report.overallSeverity.toUpperCase()}`,
    `Window: last ${report.windowMinutes} min · ${report.generatedAt}`,
    "",
  ];
  for (const i of issues) {
    lines.push(
      `[${i.severity.toUpperCase()}] ${i.title} (${i.source})`,
      `  ${i.description}`,
      i.affectedResources.length ? `  Affected: ${i.affectedResources.join(", ")}` : "",
      `  → ${i.recommendation}`,
      "",
    );
  }
  return lines.join("\n");
}
